import type {
  ExtractedComplaintFacts,
  GoldenScenarioId,
  Priority,
  SubcategoryCode,
  WorkerCategoryCode,
} from "@kapas/domain";

export interface ScenarioAiOutput {
  transcriptUr: string;
  transcriptEn: string;
  summaryUr: string;
  summaryEn: string;
  suggestedCategory: WorkerCategoryCode;
  suggestedSubcategory?: SubcategoryCode;
  suggestedPriority: Priority;
  confidenceScore: number;
  humanReviewRequired: boolean;
  failed: boolean;
  extractedFacts?: ExtractedComplaintFacts;
  facts: string[];
  warnings?: string[];
}

export const GOLDEN_AI_OUTPUTS: Record<GoldenScenarioId, ScenarioAiOutput> = {
  "GS-01": {
    transcriptUr: "یزمان میں ٹھیکیدار نے کپاس چننے کی روزانہ اجرت 1200 روپے طے کی تھی، مگر تین پورے دن کے کام کے بعد صرف 800 روپے روزانہ دیے اور کہا باقی بعد میں دیکھیں گے۔ ہمارے گروپ کی چار خواتین کو بھی یہی کم رقم ملی۔",
    transcriptEn: "In Yazman, the contractor agreed to pay PKR 1,200 per day for cotton picking, but after three full days he paid only PKR 800 per day and said the rest would be adjusted later. Four women pickers in our group received the same lower amount.",
    summaryUr: "آپ نے بتایا کہ طے شدہ روزانہ اجرت سے کم ادائیگی ہوئی اور چار خواتین متاثر ہیں۔",
    summaryEn: "Worker reports agreed PKR 1,200 daily wage but received PKR 800, with four women pickers affected.",
    suggestedCategory: "WAG",
    suggestedSubcategory: "WAG-UND",
    suggestedPriority: "High",
    confidenceScore: 0.94,
    humanReviewRequired: false,
    failed: false,
    extractedFacts: { amountExpected: 1200, amountReceived: 800, affectedWorkers: "2-5" },
    facts: ["Agreed PKR 1,200 daily wage", "Received PKR 800 per day", "Four women pickers affected"],
  },
  "GS-02": {
    transcriptUr: "صبح کپاس کی قریبی قطاروں میں سپرے ہوا مگر بو ختم ہونے سے پہلے ہمیں دوبارہ کھیت میں بھیج دیا گیا۔ میری آنکھوں میں جلن، چکر اور سانس لینے میں مشکل ہے، اور ایک اور چننے والی بھی بیمار محسوس کر رہی ہے۔",
    transcriptEn: "Spray was done in the nearby cotton rows early in the morning, but we were sent back into the field before the smell cleared. I have burning eyes, dizziness and difficulty breathing, and one other picker is also feeling sick.",
    summaryUr: "آپ نے بتایا کہ سپرے کے فوراً بعد کھیت میں بھیجنے سے آنکھوں، چکر اور سانس کا مسئلہ ہوا۔",
    summaryEn: "Pesticide exposure after early re-entry, with burning eyes, dizziness and breathing difficulty.",
    suggestedCategory: "PES",
    suggestedSubcategory: "PES-SYM",
    suggestedPriority: "High",
    confidenceScore: 0.81,
    humanReviewRequired: false,
    failed: false,
    extractedFacts: { symptoms: ["breathing difficulty", "dizziness"] },
    facts: ["Early field re-entry after spray", "Burning eyes", "Breathing difficulty", "Dizziness", "Another picker sick"],
  },
  "GS-03": {
    transcriptUr: "کھیت کا نگران سب کے سامنے مجھ پر چلاتا ہے اور کہتا ہے کہ شکایت کی تو میرے گھر والوں کا کام بند کر دے گا۔ براہ کرم میرے فون پر پیغام نہ بھیجیں؛ میں صرف دوپہر کو کھیت سے دور محفوظ طریقے سے بات کر سکتی ہوں۔",
    transcriptEn: "The field supervisor shouts at me in front of other workers and said he will remove my family from work if I complain. Please do not send a message to my phone; I can only speak safely in the afternoon when I am away from the field.",
    summaryUr: "آپ نے نگران کی دھمکی، بدزبانی اور محفوظ رابطے کی محدود صورت بتائی۔",
    summaryEn: "Worker reports supervisor intimidation and requests restricted safe contact.",
    suggestedCategory: "HAR",
    suggestedSubcategory: "HAR-INT",
    suggestedPriority: "High",
    confidenceScore: 0.72,
    humanReviewRequired: true,
    failed: false,
    facts: ["Supervisor intimidation", "Threat to remove family from work", "No phone message", "Afternoon safe contact"],
  },
  "GS-04": {
    transcriptUr: "ایک بچہ جو تقریباً بارہ سال کا لگتا ہے صبح سے دیر دوپہر تک بڑوں کے ساتھ کپاس چن رہا ہے۔ سپرے کے بعد بھی وہ اسی کھیت کے قریب تھا۔ میں گمنام اطلاع دے رہا/رہی ہوں کیونکہ اس کے گھر والے کام کے لیے ٹھیکیدار پر انحصار کرتے ہیں۔",
    transcriptEn: "A boy who looks about twelve is picking cotton with adults from morning until late afternoon. He was also near the field after pesticide spray. I am reporting anonymously because the family depends on the contractor for work.",
    summaryUr: "آپ نے کم عمر بچے کے لمبے وقت تک کپاس چننے اور سپرے والی جگہ کے قریب ہونے کی اطلاع دی۔",
    summaryEn: "Anonymous report of possible child labour in cotton picking and pesticide-related risk.",
    suggestedCategory: "CHL",
    suggestedSubcategory: "CHL-HAZ",
    suggestedPriority: "Standard",
    confidenceScore: 0.88,
    humanReviewRequired: true,
    failed: false,
    facts: ["Possible underage boy", "Long picking hours", "Near sprayed field", "Anonymous reporter"],
  },
  "GS-05": {
    transcriptUr: "مزدور ٹھیکیدار کہتا ہے کہ ادھار اور سواری کا خرچ پورا کیے بغیر ہم کپاس کے کیمپ سے نہیں جا سکتے۔ اس نے دو ہفتوں کی اجرت روک لی ہے اور دوسرے فارم پر جانے سے منع کیا ہے۔",
    transcriptEn: "The labour contractor says our advance and transport cost must be cleared before we can leave the cotton camp. He has kept two weeks of wages and warned us not to go to another farm.",
    summaryUr: "آپ نے ادھار، سواری کے خرچ، روکی گئی اجرت اور نقل و حرکت پر دباؤ بتایا۔",
    summaryEn: "Worker reports debt-related restriction, withheld wages and pressure not to leave the camp.",
    suggestedCategory: "FOL",
    suggestedSubcategory: "FOL-THR",
    suggestedPriority: "High",
    confidenceScore: 0.9,
    humanReviewRequired: true,
    failed: false,
    facts: ["Advance and transport debt", "Two weeks wages withheld", "Pressure not to leave camp"],
  },
  "GS-06": {
    transcriptUr: "میں اپنے چنائی والے گروپ کی طرف سے بتا رہی ہوں۔ بیس سے زیادہ مزدوروں کو پچھلے دو ہفتوں کی اجرت نہیں ملی، حالانکہ روز کپاس کا وزن ہوا اور منشی نے ہمارے نام رجسٹر میں لکھے۔",
    transcriptEn: "I am reporting for our picking group. More than twenty workers have not received wages for the last two weeks, although cotton was weighed daily and the munshi wrote our names in his register.",
    summaryUr: "آپ نے بتایا کہ بیس سے زیادہ مزدوروں کی دو ہفتوں کی اجرت رکی ہوئی ہے۔",
    summaryEn: "Representative reports two weeks of unpaid wages for more than twenty cotton pickers.",
    suggestedCategory: "WAG",
    suggestedSubcategory: "WAG-DEL",
    suggestedPriority: "High",
    confidenceScore: 0.91,
    humanReviewRequired: false,
    failed: false,
    extractedFacts: { affectedWorkers: "more-than-20" },
    facts: ["More than 20 workers", "Two weeks unpaid", "Daily weighing recorded by munshi"],
  },
  "GS-07": {
    transcriptUr: "کپاس چننے والی جگہ کے قریب صاف پینے کا پانی یا الگ بیت الخلا نہیں ہے۔ خواتین مزدوروں کو کھیت سے دور جانا پڑتا ہے، اور نہری پانی پینے کے بعد کئی لوگوں کے پیٹ میں درد ہوا ہے۔",
    transcriptEn: "There is no clean drinking water or separate toilet near the cotton picking area. Women workers walk far from the field, and several people have stomach pain after drinking canal water.",
    summaryUr: "آپ نے صاف پانی، الگ بیت الخلا اور نہری پانی سے بیماری کا مسئلہ بتایا۔",
    summaryEn: "Worker reports lack of drinking water and separate toilet facilities near the picking area.",
    suggestedCategory: "SAN",
    suggestedSubcategory: "SAN-WAT",
    suggestedPriority: "Standard",
    confidenceScore: 0.86,
    humanReviewRequired: false,
    failed: false,
    facts: ["No clean drinking water", "No separate toilet", "Women walk far", "Stomach pain after canal water"],
  },
  "GS-08": {
    transcriptUr: "ریکارڈنگ سڑک کے قریب ہونے کی وجہ سے شور والی ہے۔ مزدور کپاس کے کام، کٹوتی اور ٹھیکیدار کا ذکر کرتا ہے، مگر درست مسئلہ سمجھنے کے لیے دوبارہ رابطہ ضروری ہے۔",
    transcriptEn: "The recording is noisy because it was made near the road. The worker mentions cotton work, deductions and a contractor, but the exact issue needs a follow-up call before classification.",
    summaryUr: "آپ کی بات کا کچھ حصہ سمجھا گیا۔ تصدیق کر لیں۔",
    summaryEn: "Partial understanding. Category suggestion is uncertain.",
    suggestedCategory: "OTH",
    suggestedPriority: "Standard",
    confidenceScore: 0.55,
    humanReviewRequired: true,
    failed: false,
    warnings: ["Low confidence"],
    facts: ["Noisy recording", "Mentions deductions", "Mentions contractor", "Follow-up needed"],
  },
  "GS-09": {
    transcriptUr: "",
    transcriptEn: "",
    summaryUr: "",
    summaryEn: "",
    suggestedCategory: "HSE",
    suggestedSubcategory: "HSE-INJ",
    suggestedPriority: "High",
    confidenceScore: 0,
    humanReviewRequired: true,
    failed: true,
    warnings: ["AI summary unavailable"],
    facts: [],
  },
  "GS-10": {
    transcriptUr: "پہلے جائزے کے بعد ٹھیکیدار نے بقایا رقم دینے کا وعدہ کیا تھا، مگر مجھے ابھی تک پیسے نہیں ملے۔ اب وہ کہتا ہے کہ پہلے سواری اور کھانے کی کٹوتی ہوگی، اس لیے میں پہلے نتیجے سے مطمئن نہیں ہوں۔",
    transcriptEn: "The contractor promised to release the pending payment after the first review, but I still have not received the money. He now says deductions for transport and food will be taken first, so I am not satisfied with the earlier result.",
    summaryUr: "آپ نے بتایا کہ پہلے وعدے کے باوجود بقایا ادائیگی نہیں ملی اور نئی کٹوتیاں لگائی جا رہی ہیں۔",
    summaryEn: "Worker reports promised payment was not received and new deductions were added after the prior resolution.",
    suggestedCategory: "CON",
    suggestedSubcategory: "CON-PAY",
    suggestedPriority: "High",
    confidenceScore: 0.89,
    humanReviewRequired: false,
    failed: false,
    facts: ["Promised payment not received", "Transport and food deductions", "Worker not satisfied"],
  },
};

export const CATEGORY_FALLBACK_OUTPUTS: Partial<Record<string, ScenarioAiOutput>> = {
  HSE: {
    transcriptUr: "کام پر چوٹ لگی ہے۔ علاج اور حفاظت کا مسئلہ ہے۔",
    transcriptEn: "Injury at work. Treatment and safety are the concern.",
    summaryUr: "آپ نے بتایا کہ کام پر چوٹ یا غیر محفوظ حالت ہے۔",
    summaryEn: "Injury or unsafe work reported.",
    suggestedCategory: "HSE",
    suggestedSubcategory: "HSE-INJ",
    suggestedPriority: "High",
    confidenceScore: 0.83,
    humanReviewRequired: false,
    failed: false,
    facts: ["Workplace injury"],
  },
  HRS: {
    transcriptUr: "کام کے گھنٹے بہت زیادہ ہیں اور آرام نہیں ملتا۔",
    transcriptEn: "Working hours are excessive and rest is not given.",
    summaryUr: "آپ نے بتایا کہ کام کے گھنٹے زیادہ ہیں۔",
    summaryEn: "Excessive working hours reported.",
    suggestedCategory: "HRS",
    suggestedSubcategory: "HRS-EXC",
    suggestedPriority: "Standard",
    confidenceScore: 0.8,
    humanReviewRequired: false,
    failed: false,
    facts: ["Excessive hours"],
  },
  DIS: {
    transcriptUr: "کچھ مزدوروں کے ساتھ الگ سلوک ہو رہا ہے۔",
    transcriptEn: "Some workers are treated differently.",
    summaryUr: "آپ نے بتایا کہ سلوک برابر نہیں۔",
    summaryEn: "Unequal treatment reported.",
    suggestedCategory: "DIS",
    suggestedSubcategory: "DIS-OTH",
    suggestedPriority: "High",
    confidenceScore: 0.78,
    humanReviewRequired: false,
    failed: false,
    facts: ["Unequal treatment"],
  },
};
