import { CATEGORY_ENTRY, type QuestionNode } from "../workflow";

export const commonNodes: QuestionNode[] = [
  {
    id: "identity",
    promptKey: "grievance.identity.prompt",
    helperKey: "grievance.identity.body",
    type: "cnic",
    section: "intro",
    next: { type: "node", id: "category" },
  },
  {
    id: "category",
    promptKey: "grievance.category.prompt",
    type: "single",
    section: "category",
    storeAs: "category",
    options: [
      { value: "WAG", labelKey: "category.WAG" },
      { value: "PES", labelKey: "category.PES" },
      { value: "HSE", labelKey: "category.HSE" },
      { value: "HAR", labelKey: "category.HAR" },
      { value: "CHL", labelKey: "category.CHL" },
      { value: "FOL", labelKey: "category.FOL" },
      { value: "more", labelKey: "category.more" },
      { value: "OTH", labelKey: "category.OTH" },
    ],
    next: {
      type: "map",
      cases: {
        ...CATEGORY_ENTRY,
        more: "category-more",
      },
      fallback: "voice",
    },
  },
  {
    id: "category-more",
    promptKey: "grievance.category.morePrompt",
    type: "single",
    section: "category",
    storeAs: "category",
    options: [
      { value: "CON", labelKey: "category.CON" },
      { value: "HRS", labelKey: "category.HRS" },
      { value: "SAN", labelKey: "category.SAN" },
      { value: "DIS", labelKey: "category.DIS" },
    ],
    next: {
      type: "map",
      cases: CATEGORY_ENTRY,
      fallback: "voice",
    },
  },
  {
    id: "voice",
    promptKey: "grievance.voice.prompt",
    helperKey: "grievance.voice.body",
    type: "voice",
    required: false,
    section: "facts",
    next: { type: "node", id: "when" },
  },
  {
    id: "when",
    promptKey: "grievance.when.prompt",
    type: "date",
    section: "facts",
    storeAs: "whenLabel",
    options: [
      { value: "today", labelKey: "when.today" },
      { value: "yesterday", labelKey: "when.yesterday" },
      { value: "week", labelKey: "when.week" },
      { value: "older", labelKey: "when.older" },
      { value: "unsure", labelKey: "when.unsure" },
    ],
    next: { type: "node", id: "where-current" },
  },
  {
    id: "where-current",
    promptKey: "grievance.where.currentPrompt",
    helperKey: "grievance.where.currentBody",
    type: "current-location",
    section: "facts",
    next: { type: "node", id: "others" },
  },
  {
    id: "where-province",
    promptKey: "grievance.where.provincePrompt",
    type: "single",
    section: "facts",
    storeAs: "province",
    options: [
      { value: "Punjab", labelKey: "province.Punjab" },
      { value: "Sindh", labelKey: "province.Sindh" },
      { value: "Khyber Pakhtunkhwa", labelKey: "province.KhyberPakhtunkhwa" },
      { value: "Balochistan", labelKey: "province.Balochistan" },
      { value: "Islamabad Capital Territory", labelKey: "province.Islamabad" },
      { value: "Gilgit-Baltistan", labelKey: "province.GilgitBaltistan" },
      { value: "Azad Jammu and Kashmir", labelKey: "province.AJK" },
    ],
    next: { type: "node", id: "where-city" },
  },
  {
    id: "where-city",
    promptKey: "grievance.where.cityPrompt",
    helperKey: "grievance.where.cityBody",
    type: "text",
    section: "facts",
    storeAs: "district",
    next: { type: "node", id: "where-place" },
  },
  {
    id: "where-place",
    promptKey: "grievance.where.placePrompt",
    helperKey: "grievance.where.placeBody",
    type: "text",
    section: "facts",
    storeAs: "placeLabel",
    next: { type: "node", id: "others" },
  },
  {
    id: "others",
    promptKey: "grievance.others.prompt",
    type: "single",
    section: "facts",
    options: [
      { value: "no", labelKey: "others.no" },
      { value: "yes", labelKey: "others.yes" },
    ],
    next: {
      type: "conditional",
      cases: [
        { when: { others: "yes" }, id: "others-range" },
        { when: { category: ["PES", "HSE", "CHL", "FOL"] }, id: "danger" },
        { when: { "wag-threat": ["yes", "unsafe"] }, id: "danger" },
        { when: { "con-what": ["abuse", "fee", "documents", "movement"] }, id: "danger" },
        { when: { "hrs-health": "yes" }, id: "danger" },
        { when: { "san-risk": "yes" }, id: "danger" },
        { when: { "dis-impact": ["threat", "abuse"] }, id: "danger" },
        { when: { "oth-urgent": "yes" }, id: "danger" },
      ],
      fallback: "privacy",
    },
  },
  {
    id: "others-range",
    promptKey: "grievance.others.rangePrompt",
    type: "single",
    section: "facts",
    storeAs: "othersAffected",
    options: [
      { value: "2-5", labelKey: "range.2-5" },
      { value: "6-20", labelKey: "range.6-20" },
      { value: "more-than-20", labelKey: "range.20+" },
      { value: "not-sure", labelKey: "range.unsure" },
    ],
    next: {
      type: "conditional",
      cases: [
        { when: { category: ["PES", "HSE", "CHL", "FOL"] }, id: "danger" },
        { when: { "wag-threat": ["yes", "unsafe"] }, id: "danger" },
        { when: { "con-what": ["abuse", "fee", "documents", "movement"] }, id: "danger" },
        { when: { "hrs-health": "yes" }, id: "danger" },
        { when: { "san-risk": "yes" }, id: "danger" },
        { when: { "dis-impact": ["threat", "abuse"] }, id: "danger" },
        { when: { "oth-urgent": "yes" }, id: "danger" },
      ],
      fallback: "privacy",
    },
  },
  {
    id: "danger",
    promptKey: "grievance.danger.prompt",
    type: "single",
    section: "safety",
    storeAs: "immediateDanger",
    options: [
      { value: "yes", labelKey: "danger.yes" },
      { value: "no", labelKey: "danger.no" },
    ],
    next: {
      type: "map",
      cases: { yes: "danger-notice", no: "privacy" },
      fallback: "privacy",
    },
  },
  {
    id: "danger-notice",
    promptKey: "grievance.danger.noticeTitle",
    helperKey: "grievance.danger.noticeBody",
    type: "notice",
    required: false,
    section: "safety",
    next: { type: "node", id: "privacy" },
  },
  {
    id: "privacy",
    promptKey: "grievance.privacy.prompt",
    type: "single",
    section: "safety",
    storeAs: "privacyMode",
    options: [
      { value: "ANON", labelKey: "privacy.ANON", helperKey: "privacy.ANON.help" },
      { value: "CONF", labelKey: "privacy.CONF", helperKey: "privacy.CONF.help" },
      { value: "IDEN", labelKey: "privacy.IDEN", helperKey: "privacy.IDEN.help" },
    ],
    next: { type: "node", id: "evidence" },
  },
  {
    id: "evidence",
    promptKey: "grievance.evidence.prompt",
    helperKey: "grievance.evidence.body",
    type: "evidence",
    required: false,
    section: "review",
    next: {
      type: "map",
      by: "privacy",
      cases: { ANON: "ai-processing", CONF: "contact", IDEN: "contact" },
      fallback: "ai-processing",
    },
  },
  {
    id: "contact",
    promptKey: "grievance.contact.prompt",
    helperKey: "contact.skipHint",
    type: "single",
    required: false,
    section: "review",
    storeAs: "contactPreference",
    options: [
      { value: "call", labelKey: "contact.call" },
      { value: "message", labelKey: "contact.message" },
      { value: "callOnly", labelKey: "contact.callOnly" },
      { value: "noMessage", labelKey: "contact.noMessage" },
      { value: "none", labelKey: "contact.none" },
      { value: "alternate", labelKey: "contact.alternate" },
    ],
    next: { type: "node", id: "ai-processing" },
  },
  {
    id: "ai-processing",
    promptKey: "grievance.ai.processing",
    type: "ai-processing",
    required: false,
    section: "ai",
    next: { type: "node", id: "ai-understanding" },
  },
  {
    id: "ai-understanding",
    promptKey: "grievance.ai.prompt",
    type: "ai-understanding",
    required: false,
    section: "ai",
    next: { type: "node", id: "review" },
  },
  {
    id: "review",
    promptKey: "grievance.review.prompt",
    type: "review",
    required: false,
    section: "review",
    next: { type: "end" },
  },
];
