import type { RightsTopic } from "@kapas/domain";

export const RIGHTS_TOPICS: RightsTopic[] = [
  {
    id: "wages",
    titleKey: "rights.wages.title",
    bodyKey: "rights.wages.body",
    tier: "core",
    tone: "gold",
    visual: "wages",
    categoryCode: "WAG",
    guidanceKeys: ["rights.wages.guidance.1", "rights.wages.guidance.2"],
    warningKeys: ["rights.wages.warning.1", "rights.wages.warning.2"],
    actionKeys: ["rights.wages.action.1", "rights.wages.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.wages.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.wages.province.Sindh",
        sourceLabelKey: "rights.source.sindhWomen",
        sourceUrl: "http://www.sindhlaws.gov.pk/setup/Publications/PUB-20-000028.pdf",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "pesticide",
    titleKey: "rights.pesticide.title",
    bodyKey: "rights.pesticide.body",
    tier: "core",
    tone: "teal",
    visual: "pesticide",
    categoryCode: "PES",
    guidanceKeys: ["rights.pesticide.guidance.1", "rights.pesticide.guidance.2"],
    warningKeys: ["rights.pesticide.warning.1", "rights.pesticide.warning.2"],
    actionKeys: ["rights.pesticide.action.1", "rights.pesticide.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.pesticide.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.pesticide.province.Sindh",
        sourceLabelKey: "rights.source.pesticideStudy",
        sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/31200258/",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "heat-hours",
    titleKey: "rights.heat.title",
    bodyKey: "rights.heat.body",
    tier: "core",
    tone: "gold",
    visual: "heat",
    categoryCode: "HRS",
    guidanceKeys: ["rights.heat.guidance.1", "rights.heat.guidance.2"],
    warningKeys: ["rights.heat.warning.1", "rights.heat.warning.2"],
    actionKeys: ["rights.heat.action.1", "rights.heat.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.heat.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.heat.province.Sindh",
        sourceLabelKey: "rights.source.sindhWomen",
        sourceUrl: "http://www.sindhlaws.gov.pk/setup/Publications/PUB-20-000028.pdf",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "injury-safety",
    titleKey: "rights.injury.title",
    bodyKey: "rights.injury.body",
    tier: "core",
    tone: "teal",
    visual: "injury",
    categoryCode: "HSE",
    guidanceKeys: ["rights.injury.guidance.1", "rights.injury.guidance.2"],
    warningKeys: ["rights.injury.warning.1", "rights.injury.warning.2"],
    actionKeys: ["rights.injury.action.1", "rights.injury.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.injury.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.injury.province.Sindh",
        sourceLabelKey: "rights.source.iloMapping",
        sourceUrl: "https://www.ilo.org/publications/mapping-cotton-supply-chain-community-level-pakistan-report-selected",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "harassment-equality",
    titleKey: "rights.equality.title",
    bodyKey: "rights.equality.body",
    tier: "core",
    tone: "red",
    visual: "equality",
    categoryCode: "HAR",
    guidanceKeys: ["rights.equality.guidance.1", "rights.equality.guidance.2"],
    warningKeys: ["rights.equality.warning.1", "rights.equality.warning.2"],
    actionKeys: ["rights.equality.action.1", "rights.equality.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.equality.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.equality.province.Sindh",
        sourceLabelKey: "rights.source.sindhWomen",
        sourceUrl: "http://www.sindhlaws.gov.pk/setup/Publications/PUB-20-000028.pdf",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "child-labour",
    titleKey: "rights.child.title",
    bodyKey: "rights.child.body",
    tier: "core",
    tone: "red",
    visual: "child",
    categoryCode: "CHL",
    guidanceKeys: ["rights.child.guidance.1", "rights.child.guidance.2"],
    warningKeys: ["rights.child.warning.1", "rights.child.warning.2"],
    actionKeys: ["rights.child.action.1", "rights.child.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.child.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.child.province.Sindh",
        sourceLabelKey: "rights.source.sindhChild",
        sourceUrl: "https://www.sindhlaws.gov.pk/setup/publications_SindhCode/PUB-NEW-18-000183.pdf",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "forced-labour",
    titleKey: "rights.forced.title",
    bodyKey: "rights.forced.body",
    tier: "core",
    tone: "red",
    visual: "freedom",
    categoryCode: "FOL",
    guidanceKeys: ["rights.forced.guidance.1", "rights.forced.guidance.2"],
    warningKeys: ["rights.forced.warning.1", "rights.forced.warning.2"],
    actionKeys: ["rights.forced.action.1", "rights.forced.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.forced.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.forced.province.Sindh",
        sourceLabelKey: "rights.source.bondedAct",
        sourceUrl: "https://pakistancode.gov.pk/pdffiles/administrator193484c31f7b4b5c5cbd0aae5038201e.pdf",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "facilities",
    titleKey: "rights.facilities.title",
    bodyKey: "rights.facilities.body",
    tier: "core",
    tone: "teal",
    visual: "facilities",
    categoryCode: "SAN",
    guidanceKeys: ["rights.facilities.guidance.1", "rights.facilities.guidance.2"],
    warningKeys: ["rights.facilities.warning.1", "rights.facilities.warning.2"],
    actionKeys: ["rights.facilities.action.1", "rights.facilities.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.facilities.province.Punjab",
        sourceLabelKey: "rights.source.iloVoice",
        sourceUrl: "https://www.ilo.org/about/newsroom/voice-women-cotton-workers-pakistan",
      },
      {
        province: "Sindh",
        bodyKey: "rights.facilities.province.Sindh",
        sourceLabelKey: "rights.source.sindhWomen",
        sourceUrl: "http://www.sindhlaws.gov.pk/setup/Publications/PUB-20-000028.pdf",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "contractor-terms",
    titleKey: "rights.contract.title",
    bodyKey: "rights.contract.body",
    tier: "more",
    tone: "gold",
    visual: "contract",
    categoryCode: "CON",
    guidanceKeys: ["rights.contract.guidance.1", "rights.contract.guidance.2"],
    warningKeys: ["rights.contract.warning.1", "rights.contract.warning.2"],
    actionKeys: ["rights.contract.action.1", "rights.contract.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.contract.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.contract.province.Sindh",
        sourceLabelKey: "rights.source.sindhWomen",
        sourceUrl: "http://www.sindhlaws.gov.pk/setup/Publications/PUB-20-000028.pdf",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "women-maternity",
    titleKey: "rights.maternity.title",
    bodyKey: "rights.maternity.body",
    tier: "more",
    tone: "gold",
    visual: "maternity",
    categoryCode: "DIS",
    guidanceKeys: ["rights.maternity.guidance.1", "rights.maternity.guidance.2"],
    warningKeys: ["rights.maternity.warning.1", "rights.maternity.warning.2"],
    actionKeys: ["rights.maternity.action.1", "rights.maternity.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.maternity.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.maternity.province.Sindh",
        sourceLabelKey: "rights.source.sindhWomen",
        sourceUrl: "http://www.sindhlaws.gov.pk/setup/Publications/PUB-20-000028.pdf",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "worker-voice",
    titleKey: "rights.voice.title",
    bodyKey: "rights.voice.body",
    tier: "more",
    tone: "green",
    visual: "collective",
    guidanceKeys: ["rights.voice.guidance.1", "rights.voice.guidance.2"],
    warningKeys: ["rights.voice.warning.1", "rights.voice.warning.2"],
    actionKeys: ["rights.voice.action.1", "rights.voice.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.voice.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.voice.province.Sindh",
        sourceLabelKey: "rights.source.sindhWomen",
        sourceUrl: "http://www.sindhlaws.gov.pk/setup/Publications/PUB-20-000028.pdf",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "compensation",
    titleKey: "rights.compensation.title",
    bodyKey: "rights.compensation.body",
    tier: "more",
    tone: "teal",
    visual: "compensation",
    categoryCode: "HSE",
    guidanceKeys: ["rights.compensation.guidance.1", "rights.compensation.guidance.2"],
    warningKeys: ["rights.compensation.warning.1", "rights.compensation.warning.2"],
    actionKeys: ["rights.compensation.action.1", "rights.compensation.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.compensation.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.compensation.province.Sindh",
        sourceLabelKey: "rights.source.iloMapping",
        sourceUrl: "https://www.ilo.org/publications/mapping-cotton-supply-chain-community-level-pakistan-report-selected",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
  {
    id: "migrant-tenant",
    titleKey: "rights.migrant.title",
    bodyKey: "rights.migrant.body",
    tier: "more",
    tone: "green",
    visual: "migrant",
    categoryCode: "DIS",
    guidanceKeys: ["rights.migrant.guidance.1", "rights.migrant.guidance.2"],
    warningKeys: ["rights.migrant.warning.1", "rights.migrant.warning.2"],
    actionKeys: ["rights.migrant.action.1", "rights.migrant.action.2"],
    provinceNotes: [
      {
        province: "Punjab",
        bodyKey: "rights.migrant.province.Punjab",
        sourceLabelKey: "rights.source.punjabCode",
        sourceUrl: "https://clr.org.pk/Labour-Laws/Punjab/Punjab%20Labour%20Code%202026..pdf",
      },
      {
        province: "Sindh",
        bodyKey: "rights.migrant.province.Sindh",
        sourceLabelKey: "rights.source.iloMapping",
        sourceUrl: "https://www.ilo.org/publications/mapping-cotton-supply-chain-community-level-pakistan-report-selected",
      },
    ],
    lastReviewedAt: "2026-08-21",
  },
];
